/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_util_ResourceBundle */

/* SYMBOL: java_util_ResourceBundle_getClassContext()[Ljava/lang/Class; */
void
Kaffe_java_util_ResourceBundle_getClassContext_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_util_ResourceBundle_getClassContext(void*);
	HArrayOfObject* ret = java_util_ResourceBundle_getClassContext(0);
	return_ref(ret);
}
