/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_reflect_Array */

/* SYMBOL: java_lang_reflect_Array_getLength(Ljava/lang/Object;)I */
void
Kaffe_java_lang_reflect_Array_getLength_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_reflect_Array_getLength(void*);
	jint ret = java_lang_reflect_Array_getLength(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_reflect_Array_get(Ljava/lang/Object;I)Ljava/lang/Object; */
void
Kaffe_java_lang_reflect_Array_get_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_lang_reflect_Array_get(void*, jint);
	struct Hjava_lang_Object* ret = java_lang_reflect_Array_get(_P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_lang_reflect_Array_getBoolean(Ljava/lang/Object;I)Z */
void
Kaffe_java_lang_reflect_Array_getBoolean_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_reflect_Array_getBoolean(void*, jint);
	jbool ret = java_lang_reflect_Array_getBoolean(_P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_lang_reflect_Array_getByte(Ljava/lang/Object;I)B */
void
Kaffe_java_lang_reflect_Array_getByte_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbyte java_lang_reflect_Array_getByte(void*, jint);
	jbyte ret = java_lang_reflect_Array_getByte(_P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_lang_reflect_Array_getChar(Ljava/lang/Object;I)C */
void
Kaffe_java_lang_reflect_Array_getChar_stub(stack_item* _P_, stack_item* _R_)
{
	extern jchar java_lang_reflect_Array_getChar(void*, jint);
	jchar ret = java_lang_reflect_Array_getChar(_P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_lang_reflect_Array_getShort(Ljava/lang/Object;I)S */
void
Kaffe_java_lang_reflect_Array_getShort_stub(stack_item* _P_, stack_item* _R_)
{
	extern jshort java_lang_reflect_Array_getShort(void*, jint);
	jshort ret = java_lang_reflect_Array_getShort(_P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_lang_reflect_Array_getInt(Ljava/lang/Object;I)I */
void
Kaffe_java_lang_reflect_Array_getInt_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_reflect_Array_getInt(void*, jint);
	jint ret = java_lang_reflect_Array_getInt(_P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_lang_reflect_Array_getLong(Ljava/lang/Object;I)J */
void
Kaffe_java_lang_reflect_Array_getLong_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_lang_reflect_Array_getLong(void*, jint);
	jlong ret = java_lang_reflect_Array_getLong(_P_[1].p, _P_[0].i);
	return_long(ret);
}

/* SYMBOL: java_lang_reflect_Array_getFloat(Ljava/lang/Object;I)F */
void
Kaffe_java_lang_reflect_Array_getFloat_stub(stack_item* _P_, stack_item* _R_)
{
	extern jfloat java_lang_reflect_Array_getFloat(void*, jint);
	jfloat ret = java_lang_reflect_Array_getFloat(_P_[1].p, _P_[0].i);
	return_float(ret);
}

/* SYMBOL: java_lang_reflect_Array_getDouble(Ljava/lang/Object;I)D */
void
Kaffe_java_lang_reflect_Array_getDouble_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_reflect_Array_getDouble(void*, jint);
	jdouble ret = java_lang_reflect_Array_getDouble(_P_[1].p, _P_[0].i);
	return_double(ret);
}

/* SYMBOL: java_lang_reflect_Array_set(Ljava/lang/Object;ILjava/lang/Object;)V */
void
Kaffe_java_lang_reflect_Array_set_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_set(void*, jint, void*);
	java_lang_reflect_Array_set(_P_[2].p, _P_[1].i, _P_[0].p);
}

/* SYMBOL: java_lang_reflect_Array_setBoolean(Ljava/lang/Object;IZ)V */
void
Kaffe_java_lang_reflect_Array_setBoolean_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_setBoolean(void*, jint, jbool);
	java_lang_reflect_Array_setBoolean(_P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_lang_reflect_Array_setByte(Ljava/lang/Object;IB)V */
void
Kaffe_java_lang_reflect_Array_setByte_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_setByte(void*, jint, jbyte);
	java_lang_reflect_Array_setByte(_P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_lang_reflect_Array_setChar(Ljava/lang/Object;IC)V */
void
Kaffe_java_lang_reflect_Array_setChar_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_setChar(void*, jint, jchar);
	java_lang_reflect_Array_setChar(_P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_lang_reflect_Array_setShort(Ljava/lang/Object;IS)V */
void
Kaffe_java_lang_reflect_Array_setShort_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_setShort(void*, jint, jshort);
	java_lang_reflect_Array_setShort(_P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_lang_reflect_Array_setInt(Ljava/lang/Object;II)V */
void
Kaffe_java_lang_reflect_Array_setInt_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_setInt(void*, jint, jint);
	java_lang_reflect_Array_setInt(_P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_lang_reflect_Array_setLong(Ljava/lang/Object;IJ)V */
void
Kaffe_java_lang_reflect_Array_setLong_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_setLong(void*, jint, jlong);
	java_lang_reflect_Array_setLong(_P_[3].p, _P_[2].i, _P_[0].l);
}

/* SYMBOL: java_lang_reflect_Array_setFloat(Ljava/lang/Object;IF)V */
void
Kaffe_java_lang_reflect_Array_setFloat_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_setFloat(void*, jint, jfloat);
	java_lang_reflect_Array_setFloat(_P_[2].p, _P_[1].i, _P_[0].f);
}

/* SYMBOL: java_lang_reflect_Array_setDouble(Ljava/lang/Object;ID)V */
void
Kaffe_java_lang_reflect_Array_setDouble_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_reflect_Array_setDouble(void*, jint, jdouble);
	java_lang_reflect_Array_setDouble(_P_[3].p, _P_[2].i, _P_[0].d);
}

/* SYMBOL: java_lang_reflect_Array_newArray(Ljava/lang/Class;I)Ljava/lang/Object; */
void
Kaffe_java_lang_reflect_Array_newArray_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_lang_reflect_Array_newArray(void*, jint);
	struct Hjava_lang_Object* ret = java_lang_reflect_Array_newArray(_P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_lang_reflect_Array_multiNewArray(Ljava/lang/Class;[I)Ljava/lang/Object; */
void
Kaffe_java_lang_reflect_Array_multiNewArray_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_lang_reflect_Array_multiNewArray(void*, HArrayOfInt*);
	struct Hjava_lang_Object* ret = java_lang_reflect_Array_multiNewArray(_P_[1].p, _P_[0].p);
	return_ref(ret);
}
