/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_reflect_Method */

/* SYMBOL: java_lang_reflect_Method_getModifiers()I */
void
Kaffe_java_lang_reflect_Method_getModifiers_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_reflect_Method_getModifiers(void*);
	jint ret = java_lang_reflect_Method_getModifiers(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_reflect_Method_invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; */
void
Kaffe_java_lang_reflect_Method_invoke_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_lang_reflect_Method_invoke(void*, void*, HArrayOfObject*);
	struct Hjava_lang_Object* ret = java_lang_reflect_Method_invoke(_P_[2].p, _P_[1].p, _P_[0].p);
	return_ref(ret);
}
