/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_io_FileOutputStream */

/* SYMBOL: java_io_FileOutputStream_open(Ljava/lang/String;)V */
void
Kaffe_java_io_FileOutputStream_open_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_FileOutputStream_open(void*, void*);
	java_io_FileOutputStream_open(_P_[1].p, _P_[0].p);
}

/* SYMBOL: java_io_FileOutputStream_openAppend(Ljava/lang/String;)V */
void
Kaffe_java_io_FileOutputStream_openAppend_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_FileOutputStream_openAppend(void*, void*);
	java_io_FileOutputStream_openAppend(_P_[1].p, _P_[0].p);
}

/* SYMBOL: java_io_FileOutputStream_write(I)V */
void
Kaffe_java_io_FileOutputStream_write_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_FileOutputStream_write(void*, jint);
	java_io_FileOutputStream_write(_P_[1].p, _P_[0].i);
}

/* SYMBOL: java_io_FileOutputStream_writeBytes([BII)V */
void
Kaffe_java_io_FileOutputStream_writeBytes_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_FileOutputStream_writeBytes(void*, HArrayOfByte*, jint, jint);
	java_io_FileOutputStream_writeBytes(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_io_FileOutputStream_close()V */
void
Kaffe_java_io_FileOutputStream_close_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_FileOutputStream_close(void*);
	java_io_FileOutputStream_close(_P_[0].p);
}
