/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_io_FileInputStream */

/* SYMBOL: java_io_FileInputStream_open(Ljava/lang/String;)V */
void
Kaffe_java_io_FileInputStream_open_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_FileInputStream_open(void*, void*);
	java_io_FileInputStream_open(_P_[1].p, _P_[0].p);
}

/* SYMBOL: java_io_FileInputStream_read()I */
void
Kaffe_java_io_FileInputStream_read_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_io_FileInputStream_read(void*);
	jint ret = java_io_FileInputStream_read(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_io_FileInputStream_readBytes([BII)I */
void
Kaffe_java_io_FileInputStream_readBytes_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_io_FileInputStream_readBytes(void*, HArrayOfByte*, jint, jint);
	jint ret = java_io_FileInputStream_readBytes(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_io_FileInputStream_skip(J)J */
void
Kaffe_java_io_FileInputStream_skip_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_io_FileInputStream_skip(void*, jlong);
	jlong ret = java_io_FileInputStream_skip(_P_[2].p, _P_[0].l);
	return_long(ret);
}

/* SYMBOL: java_io_FileInputStream_available()I */
void
Kaffe_java_io_FileInputStream_available_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_io_FileInputStream_available(void*);
	jint ret = java_io_FileInputStream_available(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_io_FileInputStream_close()V */
void
Kaffe_java_io_FileInputStream_close_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_FileInputStream_close(void*);
	java_io_FileInputStream_close(_P_[0].p);
}
