/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_io_ObjectStreamClass */

/* SYMBOL: java_io_ObjectStreamClass_getClassAccess(Ljava/lang/Class;)I */
void
Kaffe_java_io_ObjectStreamClass_getClassAccess_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_io_ObjectStreamClass_getClassAccess(void*);
	jint ret = java_io_ObjectStreamClass_getClassAccess(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_io_ObjectStreamClass_getMethodSignatures(Ljava/lang/Class;)[Ljava/lang/String; */
void
Kaffe_java_io_ObjectStreamClass_getMethodSignatures_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_io_ObjectStreamClass_getMethodSignatures(void*);
	HArrayOfObject* ret = java_io_ObjectStreamClass_getMethodSignatures(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_io_ObjectStreamClass_getMethodAccess(Ljava/lang/Class;Ljava/lang/String;)I */
void
Kaffe_java_io_ObjectStreamClass_getMethodAccess_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_io_ObjectStreamClass_getMethodAccess(void*, void*);
	jint ret = java_io_ObjectStreamClass_getMethodAccess(_P_[1].p, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_io_ObjectStreamClass_getFieldSignatures(Ljava/lang/Class;)[Ljava/lang/String; */
void
Kaffe_java_io_ObjectStreamClass_getFieldSignatures_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_io_ObjectStreamClass_getFieldSignatures(void*);
	HArrayOfObject* ret = java_io_ObjectStreamClass_getFieldSignatures(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_io_ObjectStreamClass_getFieldAccess(Ljava/lang/Class;Ljava/lang/String;)I */
void
Kaffe_java_io_ObjectStreamClass_getFieldAccess_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_io_ObjectStreamClass_getFieldAccess(void*, void*);
	jint ret = java_io_ObjectStreamClass_getFieldAccess(_P_[1].p, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_io_ObjectStreamClass_getFields0(Ljava/lang/Class;)[Ljava/io/ObjectStreamField; */
void
Kaffe_java_io_ObjectStreamClass_getFields0_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_io_ObjectStreamClass_getFields0(void*, void*);
	HArrayOfObject* ret = java_io_ObjectStreamClass_getFields0(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_io_ObjectStreamClass_getSerialVersionUID(Ljava/lang/Class;)J */
void
Kaffe_java_io_ObjectStreamClass_getSerialVersionUID_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_io_ObjectStreamClass_getSerialVersionUID(void*);
	jlong ret = java_io_ObjectStreamClass_getSerialVersionUID(_P_[0].p);
	return_long(ret);
}

/* SYMBOL: java_io_ObjectStreamClass_hasWriteObject(Ljava/lang/Class;)Z */
void
Kaffe_java_io_ObjectStreamClass_hasWriteObject_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_io_ObjectStreamClass_hasWriteObject(void*);
	jbool ret = java_io_ObjectStreamClass_hasWriteObject(_P_[0].p);
	return_int(ret);
}
