/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_io_ObjectInputStream */

/* SYMBOL: java_io_ObjectInputStream_loadClass0(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Class; */
void
Kaffe_java_io_ObjectInputStream_loadClass0_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Class* java_io_ObjectInputStream_loadClass0(void*, void*, void*);
	struct Hjava_lang_Class* ret = java_io_ObjectInputStream_loadClass0(_P_[2].p, _P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_io_ObjectInputStream_inputClassFields(Ljava/lang/Object;Ljava/lang/Class;[I)V */
void
Kaffe_java_io_ObjectInputStream_inputClassFields_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_ObjectInputStream_inputClassFields(void*, void*, void*, HArrayOfInt*);
	java_io_ObjectInputStream_inputClassFields(_P_[3].p, _P_[2].p, _P_[1].p, _P_[0].p);
}

/* SYMBOL: java_io_ObjectInputStream_allocateNewObject(Ljava/lang/Class;Ljava/lang/Class;)Ljava/lang/Object; */
void
Kaffe_java_io_ObjectInputStream_allocateNewObject_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_io_ObjectInputStream_allocateNewObject(void*, void*);
	struct Hjava_lang_Object* ret = java_io_ObjectInputStream_allocateNewObject(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_io_ObjectInputStream_allocateNewArray(Ljava/lang/Class;I)Ljava/lang/Object; */
void
Kaffe_java_io_ObjectInputStream_allocateNewArray_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_io_ObjectInputStream_allocateNewArray(void*, jint);
	struct Hjava_lang_Object* ret = java_io_ObjectInputStream_allocateNewArray(_P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_io_ObjectInputStream_invokeObjectReader(Ljava/lang/Object;Ljava/lang/Class;)Z */
void
Kaffe_java_io_ObjectInputStream_invokeObjectReader_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_io_ObjectInputStream_invokeObjectReader(void*, void*, void*);
	jbool ret = java_io_ObjectInputStream_invokeObjectReader(_P_[2].p, _P_[1].p, _P_[0].p);
	return_int(ret);
}
