/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_io_RandomAccessFile */

/* SYMBOL: java_io_RandomAccessFile_open(Ljava/lang/String;Z)V */
void
Kaffe_java_io_RandomAccessFile_open_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_RandomAccessFile_open(void*, void*, jbool);
	java_io_RandomAccessFile_open(_P_[2].p, _P_[1].p, _P_[0].i);
}

/* SYMBOL: java_io_RandomAccessFile_read()I */
void
Kaffe_java_io_RandomAccessFile_read_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_io_RandomAccessFile_read(void*);
	jint ret = java_io_RandomAccessFile_read(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_io_RandomAccessFile_readBytes([BII)I */
void
Kaffe_java_io_RandomAccessFile_readBytes_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_io_RandomAccessFile_readBytes(void*, HArrayOfByte*, jint, jint);
	jint ret = java_io_RandomAccessFile_readBytes(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_io_RandomAccessFile_write(I)V */
void
Kaffe_java_io_RandomAccessFile_write_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_RandomAccessFile_write(void*, jint);
	java_io_RandomAccessFile_write(_P_[1].p, _P_[0].i);
}

/* SYMBOL: java_io_RandomAccessFile_writeBytes([BII)V */
void
Kaffe_java_io_RandomAccessFile_writeBytes_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_RandomAccessFile_writeBytes(void*, HArrayOfByte*, jint, jint);
	java_io_RandomAccessFile_writeBytes(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_io_RandomAccessFile_getFilePointer()J */
void
Kaffe_java_io_RandomAccessFile_getFilePointer_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_io_RandomAccessFile_getFilePointer(void*);
	jlong ret = java_io_RandomAccessFile_getFilePointer(_P_[0].p);
	return_long(ret);
}

/* SYMBOL: java_io_RandomAccessFile_seek(J)V */
void
Kaffe_java_io_RandomAccessFile_seek_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_RandomAccessFile_seek(void*, jlong);
	java_io_RandomAccessFile_seek(_P_[2].p, _P_[0].l);
}

/* SYMBOL: java_io_RandomAccessFile_length()J */
void
Kaffe_java_io_RandomAccessFile_length_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_io_RandomAccessFile_length(void*);
	jlong ret = java_io_RandomAccessFile_length(_P_[0].p);
	return_long(ret);
}

/* SYMBOL: java_io_RandomAccessFile_close()V */
void
Kaffe_java_io_RandomAccessFile_close_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_io_RandomAccessFile_close(void*);
	java_io_RandomAccessFile_close(_P_[0].p);
}
