/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_util_zip_Adler32 */

/* SYMBOL: java_util_zip_Adler32_update([BII)V */
void
Kaffe_java_util_zip_Adler32_update_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_util_zip_Adler32_update(void*, HArrayOfByte*, jint, jint);
	java_util_zip_Adler32_update(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_util_zip_Adler32_update1(I)V */
void
Kaffe_java_util_zip_Adler32_update1_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_util_zip_Adler32_update1(void*, jint);
	java_util_zip_Adler32_update1(_P_[1].p, _P_[0].i);
}
