/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_util_zip_Inflater */

/* SYMBOL: java_util_zip_Inflater_setDictionary([BII)V */
void
Kaffe_java_util_zip_Inflater_setDictionary_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_util_zip_Inflater_setDictionary(void*, HArrayOfByte*, jint, jint);
	java_util_zip_Inflater_setDictionary(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_util_zip_Inflater_inflate([BII)I */
void
Kaffe_java_util_zip_Inflater_inflate_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_util_zip_Inflater_inflate(void*, HArrayOfByte*, jint, jint);
	jint ret = java_util_zip_Inflater_inflate(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_util_zip_Inflater_getAdler()I */
void
Kaffe_java_util_zip_Inflater_getAdler_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_util_zip_Inflater_getAdler(void*);
	jint ret = java_util_zip_Inflater_getAdler(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_util_zip_Inflater_getTotalIn()I */
void
Kaffe_java_util_zip_Inflater_getTotalIn_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_util_zip_Inflater_getTotalIn(void*);
	jint ret = java_util_zip_Inflater_getTotalIn(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_util_zip_Inflater_getTotalOut()I */
void
Kaffe_java_util_zip_Inflater_getTotalOut_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_util_zip_Inflater_getTotalOut(void*);
	jint ret = java_util_zip_Inflater_getTotalOut(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_util_zip_Inflater_reset()V */
void
Kaffe_java_util_zip_Inflater_reset_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_util_zip_Inflater_reset(void*);
	java_util_zip_Inflater_reset(_P_[0].p);
}

/* SYMBOL: java_util_zip_Inflater_end()V */
void
Kaffe_java_util_zip_Inflater_end_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_util_zip_Inflater_end(void*);
	java_util_zip_Inflater_end(_P_[0].p);
}

/* SYMBOL: java_util_zip_Inflater_init(Z)V */
void
Kaffe_java_util_zip_Inflater_init_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_util_zip_Inflater_init(void*, jbool);
	java_util_zip_Inflater_init(_P_[1].p, _P_[0].i);
}
