/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Class */

/* SYMBOL: java_lang_Class_forName(Ljava/lang/String;)Ljava/lang/Class; */
void
Kaffe_java_lang_Class_forName_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Class* java_lang_Class_forName(void*);
	struct Hjava_lang_Class* ret = java_lang_Class_forName(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_newInstance()Ljava/lang/Object; */
void
Kaffe_java_lang_Class_newInstance_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_lang_Class_newInstance(void*);
	struct Hjava_lang_Object* ret = java_lang_Class_newInstance(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_isInstance(Ljava/lang/Object;)Z */
void
Kaffe_java_lang_Class_isInstance_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Class_isInstance(void*, void*);
	jbool ret = java_lang_Class_isInstance(_P_[1].p, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Class_isAssignableFrom(Ljava/lang/Class;)Z */
void
Kaffe_java_lang_Class_isAssignableFrom_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Class_isAssignableFrom(void*, void*);
	jbool ret = java_lang_Class_isAssignableFrom(_P_[1].p, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Class_isInterface()Z */
void
Kaffe_java_lang_Class_isInterface_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Class_isInterface(void*);
	jbool ret = java_lang_Class_isInterface(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Class_isArray()Z */
void
Kaffe_java_lang_Class_isArray_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Class_isArray(void*);
	jbool ret = java_lang_Class_isArray(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Class_isPrimitive()Z */
void
Kaffe_java_lang_Class_isPrimitive_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Class_isPrimitive(void*);
	jbool ret = java_lang_Class_isPrimitive(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Class_getName()Ljava/lang/String; */
void
Kaffe_java_lang_Class_getName_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_lang_Class_getName(void*);
	struct Hjava_lang_String* ret = java_lang_Class_getName(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getClassLoader()Ljava/lang/ClassLoader; */
void
Kaffe_java_lang_Class_getClassLoader_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_ClassLoader* java_lang_Class_getClassLoader(void*);
	struct Hjava_lang_ClassLoader* ret = java_lang_Class_getClassLoader(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getSuperclass()Ljava/lang/Class; */
void
Kaffe_java_lang_Class_getSuperclass_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Class* java_lang_Class_getSuperclass(void*);
	struct Hjava_lang_Class* ret = java_lang_Class_getSuperclass(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getInterfaces()[Ljava/lang/Class; */
void
Kaffe_java_lang_Class_getInterfaces_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_lang_Class_getInterfaces(void*);
	HArrayOfObject* ret = java_lang_Class_getInterfaces(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getComponentType()Ljava/lang/Class; */
void
Kaffe_java_lang_Class_getComponentType_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Class* java_lang_Class_getComponentType(void*);
	struct Hjava_lang_Class* ret = java_lang_Class_getComponentType(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getModifiers()I */
void
Kaffe_java_lang_Class_getModifiers_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_Class_getModifiers(void*);
	jint ret = java_lang_Class_getModifiers(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Class_getSigners()[Ljava/lang/Object; */
void
Kaffe_java_lang_Class_getSigners_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_lang_Class_getSigners(void*);
	HArrayOfObject* ret = java_lang_Class_getSigners(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_setSigners([Ljava/lang/Object;)V */
void
Kaffe_java_lang_Class_setSigners_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Class_setSigners(void*, HArrayOfObject*);
	java_lang_Class_setSigners(_P_[1].p, _P_[0].p);
}

/* SYMBOL: java_lang_Class_getPrimitiveClass(Ljava/lang/String;)Ljava/lang/Class; */
void
Kaffe_java_lang_Class_getPrimitiveClass_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Class* java_lang_Class_getPrimitiveClass(void*);
	struct Hjava_lang_Class* ret = java_lang_Class_getPrimitiveClass(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getFields0(I)[Ljava/lang/reflect/Field; */
void
Kaffe_java_lang_Class_getFields0_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_lang_Class_getFields0(void*, jint);
	HArrayOfObject* ret = java_lang_Class_getFields0(_P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getMethods0(I)[Ljava/lang/reflect/Method; */
void
Kaffe_java_lang_Class_getMethods0_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_lang_Class_getMethods0(void*, jint);
	HArrayOfObject* ret = java_lang_Class_getMethods0(_P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getConstructors0(I)[Ljava/lang/reflect/Constructor; */
void
Kaffe_java_lang_Class_getConstructors0_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* java_lang_Class_getConstructors0(void*, jint);
	HArrayOfObject* ret = java_lang_Class_getConstructors0(_P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getField0(Ljava/lang/String;I)Ljava/lang/reflect/Field; */
void
Kaffe_java_lang_Class_getField0_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_reflect_Field* java_lang_Class_getField0(void*, void*, jint);
	struct Hjava_lang_reflect_Field* ret = java_lang_Class_getField0(_P_[2].p, _P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getMethod0(Ljava/lang/String;[Ljava/lang/Class;I)Ljava/lang/reflect/Method; */
void
Kaffe_java_lang_Class_getMethod0_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_reflect_Method* java_lang_Class_getMethod0(void*, void*, HArrayOfObject*, jint);
	struct Hjava_lang_reflect_Method* ret = java_lang_Class_getMethod0(_P_[3].p, _P_[2].p, _P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_lang_Class_getConstructor0([Ljava/lang/Class;I)Ljava/lang/reflect/Constructor; */
void
Kaffe_java_lang_Class_getConstructor0_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_reflect_Constructor* java_lang_Class_getConstructor0(void*, HArrayOfObject*, jint);
	struct Hjava_lang_reflect_Constructor* ret = java_lang_Class_getConstructor0(_P_[2].p, _P_[1].p, _P_[0].i);
	return_ref(ret);
}
