/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Class
#define _Included_java_lang_Class

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Class */

typedef struct Classjava_lang_Class {
	int __DUMMY__;
} Classjava_lang_Class;
HandleTo(java_lang_Class);

extern struct Hjava_lang_Class* java_lang_Class_forName(struct Hjava_lang_String*);
extern struct Hjava_lang_Object* java_lang_Class_newInstance(struct Hjava_lang_Class*);
extern jbool java_lang_Class_isInstance(struct Hjava_lang_Class*, struct Hjava_lang_Object*);
extern jbool java_lang_Class_isAssignableFrom(struct Hjava_lang_Class*, struct Hjava_lang_Class*);
extern jbool java_lang_Class_isInterface(struct Hjava_lang_Class*);
extern jbool java_lang_Class_isArray(struct Hjava_lang_Class*);
extern jbool java_lang_Class_isPrimitive(struct Hjava_lang_Class*);
extern struct Hjava_lang_String* java_lang_Class_getName(struct Hjava_lang_Class*);
extern struct Hjava_lang_ClassLoader* java_lang_Class_getClassLoader(struct Hjava_lang_Class*);
extern struct Hjava_lang_Class* java_lang_Class_getSuperclass(struct Hjava_lang_Class*);
extern HArrayOfObject* java_lang_Class_getInterfaces(struct Hjava_lang_Class*);
extern struct Hjava_lang_Class* java_lang_Class_getComponentType(struct Hjava_lang_Class*);
extern jint java_lang_Class_getModifiers(struct Hjava_lang_Class*);
extern HArrayOfObject* java_lang_Class_getSigners(struct Hjava_lang_Class*);
extern void java_lang_Class_setSigners(struct Hjava_lang_Class*, HArrayOfObject*);
extern struct Hjava_lang_Class* java_lang_Class_getPrimitiveClass(struct Hjava_lang_String*);
extern HArrayOfObject* java_lang_Class_getFields0(struct Hjava_lang_Class*, jint);
extern HArrayOfObject* java_lang_Class_getMethods0(struct Hjava_lang_Class*, jint);
extern HArrayOfObject* java_lang_Class_getConstructors0(struct Hjava_lang_Class*, jint);
extern struct Hjava_lang_reflect_Field* java_lang_Class_getField0(struct Hjava_lang_Class*, struct Hjava_lang_String*, jint);
extern struct Hjava_lang_reflect_Method* java_lang_Class_getMethod0(struct Hjava_lang_Class*, struct Hjava_lang_String*, HArrayOfObject*, jint);
extern struct Hjava_lang_reflect_Constructor* java_lang_Class_getConstructor0(struct Hjava_lang_Class*, HArrayOfObject*, jint);

#ifdef __cplusplus
}
#endif

#endif
