/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Compiler */

/* SYMBOL: java_lang_Compiler_initialize()V */
void
Kaffe_java_lang_Compiler_initialize_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Compiler_initialize();
	java_lang_Compiler_initialize();
}

/* SYMBOL: java_lang_Compiler_compileClass(Ljava/lang/Class;)Z */
void
Kaffe_java_lang_Compiler_compileClass_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Compiler_compileClass(void*);
	jbool ret = java_lang_Compiler_compileClass(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Compiler_compileClasses(Ljava/lang/String;)Z */
void
Kaffe_java_lang_Compiler_compileClasses_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Compiler_compileClasses(void*);
	jbool ret = java_lang_Compiler_compileClasses(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Compiler_command(Ljava/lang/Object;)Ljava/lang/Object; */
void
Kaffe_java_lang_Compiler_command_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* java_lang_Compiler_command(void*);
	struct Hjava_lang_Object* ret = java_lang_Compiler_command(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Compiler_enable()V */
void
Kaffe_java_lang_Compiler_enable_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Compiler_enable();
	java_lang_Compiler_enable();
}

/* SYMBOL: java_lang_Compiler_disable()V */
void
Kaffe_java_lang_Compiler_disable_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Compiler_disable();
	java_lang_Compiler_disable();
}
