/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Double */

/* SYMBOL: java_lang_Double_doubleToLongBits(D)J */
void
Kaffe_java_lang_Double_doubleToLongBits_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_lang_Double_doubleToLongBits(jdouble);
	jlong ret = java_lang_Double_doubleToLongBits(_P_[0].d);
	return_long(ret);
}

/* SYMBOL: java_lang_Double_longBitsToDouble(J)D */
void
Kaffe_java_lang_Double_longBitsToDouble_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Double_longBitsToDouble(jlong);
	jdouble ret = java_lang_Double_longBitsToDouble(_P_[0].l);
	return_double(ret);
}

/* SYMBOL: java_lang_Double_valueOf0(Ljava/lang/String;)D */
void
Kaffe_java_lang_Double_valueOf0_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Double_valueOf0(void*);
	jdouble ret = java_lang_Double_valueOf0(_P_[0].p);
	return_double(ret);
}
