/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Float */

/* SYMBOL: java_lang_Float_floatToIntBits(F)I */
void
Kaffe_java_lang_Float_floatToIntBits_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_Float_floatToIntBits(jfloat);
	jint ret = java_lang_Float_floatToIntBits(_P_[0].f);
	return_int(ret);
}

/* SYMBOL: java_lang_Float_intBitsToFloat(I)F */
void
Kaffe_java_lang_Float_intBitsToFloat_stub(stack_item* _P_, stack_item* _R_)
{
	extern jfloat java_lang_Float_intBitsToFloat(jint);
	jfloat ret = java_lang_Float_intBitsToFloat(_P_[0].i);
	return_float(ret);
}
