/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Math */

/* SYMBOL: java_lang_Math_sin(D)D */
void
Kaffe_java_lang_Math_sin_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_sin(jdouble);
	jdouble ret = java_lang_Math_sin(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_cos(D)D */
void
Kaffe_java_lang_Math_cos_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_cos(jdouble);
	jdouble ret = java_lang_Math_cos(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_tan(D)D */
void
Kaffe_java_lang_Math_tan_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_tan(jdouble);
	jdouble ret = java_lang_Math_tan(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_asin(D)D */
void
Kaffe_java_lang_Math_asin_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_asin(jdouble);
	jdouble ret = java_lang_Math_asin(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_acos(D)D */
void
Kaffe_java_lang_Math_acos_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_acos(jdouble);
	jdouble ret = java_lang_Math_acos(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_atan(D)D */
void
Kaffe_java_lang_Math_atan_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_atan(jdouble);
	jdouble ret = java_lang_Math_atan(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_exp(D)D */
void
Kaffe_java_lang_Math_exp_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_exp(jdouble);
	jdouble ret = java_lang_Math_exp(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_log(D)D */
void
Kaffe_java_lang_Math_log_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_log(jdouble);
	jdouble ret = java_lang_Math_log(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_sqrt(D)D */
void
Kaffe_java_lang_Math_sqrt_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_sqrt(jdouble);
	jdouble ret = java_lang_Math_sqrt(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_IEEEremainder(DD)D */
void
Kaffe_java_lang_Math_IEEEremainder_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_IEEEremainder(jdouble, jdouble);
	jdouble ret = java_lang_Math_IEEEremainder(_P_[2].d, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_ceil(D)D */
void
Kaffe_java_lang_Math_ceil_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_ceil(jdouble);
	jdouble ret = java_lang_Math_ceil(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_floor(D)D */
void
Kaffe_java_lang_Math_floor_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_floor(jdouble);
	jdouble ret = java_lang_Math_floor(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_rint(D)D */
void
Kaffe_java_lang_Math_rint_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_rint(jdouble);
	jdouble ret = java_lang_Math_rint(_P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_atan2(DD)D */
void
Kaffe_java_lang_Math_atan2_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_atan2(jdouble, jdouble);
	jdouble ret = java_lang_Math_atan2(_P_[2].d, _P_[0].d);
	return_double(ret);
}

/* SYMBOL: java_lang_Math_pow(DD)D */
void
Kaffe_java_lang_Math_pow_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble java_lang_Math_pow(jdouble, jdouble);
	jdouble ret = java_lang_Math_pow(_P_[2].d, _P_[0].d);
	return_double(ret);
}
