/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Object
#define _Included_java_lang_Object

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Object */

typedef struct Classjava_lang_Object {
	int __DUMMY__;
} Classjava_lang_Object;
HandleTo(java_lang_Object);

extern struct Hjava_lang_Class* java_lang_Object_getClass(struct Hjava_lang_Object*);
extern jint java_lang_Object_hashCode(struct Hjava_lang_Object*);
extern struct Hjava_lang_Object* java_lang_Object_clone(struct Hjava_lang_Object*);
extern void java_lang_Object_notify(struct Hjava_lang_Object*);
extern void java_lang_Object_notifyAll(struct Hjava_lang_Object*);
extern void java_lang_Object_wait(struct Hjava_lang_Object*, jlong);

#ifdef __cplusplus
}
#endif

#endif
