/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_ProcessReaper */

/* SYMBOL: java_lang_ProcessReaper_waitForDeath()V */
void
Kaffe_java_lang_ProcessReaper_waitForDeath_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_ProcessReaper_waitForDeath(void*);
	java_lang_ProcessReaper_waitForDeath(_P_[0].p);
}
