/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_ProcessReaper
#define _Included_java_lang_ProcessReaper

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_ProcessReaper */

typedef struct Classjava_lang_ProcessReaper {
