/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Runtime */

/* SYMBOL: java_lang_Runtime_exitInternal(I)V */
void
Kaffe_java_lang_Runtime_exitInternal_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Runtime_exitInternal(void*, jint);
	java_lang_Runtime_exitInternal(_P_[1].p, _P_[0].i);
}

/* SYMBOL: java_lang_Runtime_runFinalizersOnExit0(Z)V */
void
Kaffe_java_lang_Runtime_runFinalizersOnExit0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Runtime_runFinalizersOnExit0(jbool);
	java_lang_Runtime_runFinalizersOnExit0(_P_[0].i);
}

/* SYMBOL: java_lang_Runtime_execInternal([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/Process; */
void
Kaffe_java_lang_Runtime_execInternal_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Process* java_lang_Runtime_execInternal(void*, HArrayOfObject*, HArrayOfObject*);
	struct Hjava_lang_Process* ret = java_lang_Runtime_execInternal(_P_[2].p, _P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Runtime_freeMemory()J */
void
Kaffe_java_lang_Runtime_freeMemory_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_lang_Runtime_freeMemory(void*);
	jlong ret = java_lang_Runtime_freeMemory(_P_[0].p);
	return_long(ret);
}

/* SYMBOL: java_lang_Runtime_totalMemory()J */
void
Kaffe_java_lang_Runtime_totalMemory_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_lang_Runtime_totalMemory(void*);
	jlong ret = java_lang_Runtime_totalMemory(_P_[0].p);
	return_long(ret);
}

/* SYMBOL: java_lang_Runtime_gc()V */
void
Kaffe_java_lang_Runtime_gc_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Runtime_gc(void*);
	java_lang_Runtime_gc(_P_[0].p);
}

/* SYMBOL: java_lang_Runtime_runFinalization()V */
void
Kaffe_java_lang_Runtime_runFinalization_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Runtime_runFinalization(void*);
	java_lang_Runtime_runFinalization(_P_[0].p);
}

/* SYMBOL: java_lang_Runtime_traceInstructions(Z)V */
void
Kaffe_java_lang_Runtime_traceInstructions_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Runtime_traceInstructions(void*, jbool);
	java_lang_Runtime_traceInstructions(_P_[1].p, _P_[0].i);
}

/* SYMBOL: java_lang_Runtime_traceMethodCalls(Z)V */
void
Kaffe_java_lang_Runtime_traceMethodCalls_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Runtime_traceMethodCalls(void*, jbool);
	java_lang_Runtime_traceMethodCalls(_P_[1].p, _P_[0].i);
}

/* SYMBOL: java_lang_Runtime_initializeLinkerInternal()Ljava/lang/String; */
void
Kaffe_java_lang_Runtime_initializeLinkerInternal_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_lang_Runtime_initializeLinkerInternal(void*);
	struct Hjava_lang_String* ret = java_lang_Runtime_initializeLinkerInternal(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Runtime_buildLibName(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; */
void
Kaffe_java_lang_Runtime_buildLibName_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_lang_Runtime_buildLibName(void*, void*, void*);
	struct Hjava_lang_String* ret = java_lang_Runtime_buildLibName(_P_[2].p, _P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_lang_Runtime_loadFileInternal(Ljava/lang/String;)I */
void
Kaffe_java_lang_Runtime_loadFileInternal_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_Runtime_loadFileInternal(void*, void*);
	jint ret = java_lang_Runtime_loadFileInternal(_P_[1].p, _P_[0].p);
	return_int(ret);
}
