/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_System */

/* SYMBOL: java_lang_System_setIn0(Ljava/io/InputStream;)V */
void
Kaffe_java_lang_System_setIn0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_System_setIn0(void*);
	java_lang_System_setIn0(_P_[0].p);
}

/* SYMBOL: java_lang_System_setOut0(Ljava/io/PrintStream;)V */
void
Kaffe_java_lang_System_setOut0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_System_setOut0(void*);
	java_lang_System_setOut0(_P_[0].p);
}

/* SYMBOL: java_lang_System_setErr0(Ljava/io/PrintStream;)V */
void
Kaffe_java_lang_System_setErr0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_System_setErr0(void*);
	java_lang_System_setErr0(_P_[0].p);
}

/* SYMBOL: java_lang_System_currentTimeMillis()J */
void
Kaffe_java_lang_System_currentTimeMillis_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong java_lang_System_currentTimeMillis();
	jlong ret = java_lang_System_currentTimeMillis();
	return_long(ret);
}

/* SYMBOL: java_lang_System_arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V */
void
Kaffe_java_lang_System_arraycopy_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_System_arraycopy(void*, jint, void*, jint, jint);
	java_lang_System_arraycopy(_P_[4].p, _P_[3].i, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: java_lang_System_identityHashCode(Ljava/lang/Object;)I */
void
Kaffe_java_lang_System_identityHashCode_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_System_identityHashCode(void*);
	jint ret = java_lang_System_identityHashCode(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_System_initProperties(Ljava/util/Properties;)Ljava/util/Properties; */
void
Kaffe_java_lang_System_initProperties_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_util_Properties* java_lang_System_initProperties(void*);
	struct Hjava_util_Properties* ret = java_lang_System_initProperties(_P_[0].p);
	return_ref(ret);
}
