/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Thread */

/* SYMBOL: java_lang_Thread_currentThread()Ljava/lang/Thread; */
void
Kaffe_java_lang_Thread_currentThread_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Thread* java_lang_Thread_currentThread();
	struct Hjava_lang_Thread* ret = java_lang_Thread_currentThread();
	return_ref(ret);
}

/* SYMBOL: java_lang_Thread_yield()V */
void
Kaffe_java_lang_Thread_yield_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Thread_yield();
	java_lang_Thread_yield();
}

/* SYMBOL: java_lang_Thread_sleep(J)V */
void
Kaffe_java_lang_Thread_sleep_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Thread_sleep(jlong);
	java_lang_Thread_sleep(_P_[0].l);
}

/* SYMBOL: java_lang_Thread_start()V */
void
Kaffe_java_lang_Thread_start_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Thread_start(void*);
	java_lang_Thread_start(_P_[0].p);
}

/* SYMBOL: java_lang_Thread_isInterrupted(Z)Z */
void
Kaffe_java_lang_Thread_isInterrupted_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Thread_isInterrupted(void*, jbool);
	jbool ret = java_lang_Thread_isInterrupted(_P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: java_lang_Thread_isAlive()Z */
void
Kaffe_java_lang_Thread_isAlive_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool java_lang_Thread_isAlive(void*);
	jbool ret = java_lang_Thread_isAlive(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Thread_countStackFrames()I */
void
Kaffe_java_lang_Thread_countStackFrames_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_Thread_countStackFrames(void*);
	jint ret = java_lang_Thread_countStackFrames(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_Thread_setPriority0(I)V */
void
Kaffe_java_lang_Thread_setPriority0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Thread_setPriority0(void*, jint);
	java_lang_Thread_setPriority0(_P_[1].p, _P_[0].i);
}

/* SYMBOL: java_lang_Thread_stop0(Ljava/lang/Object;)V */
void
Kaffe_java_lang_Thread_stop0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Thread_stop0(void*, void*);
	java_lang_Thread_stop0(_P_[1].p, _P_[0].p);
}

/* SYMBOL: java_lang_Thread_suspend0()V */
void
Kaffe_java_lang_Thread_suspend0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Thread_suspend0(void*);
	java_lang_Thread_suspend0(_P_[0].p);
}

/* SYMBOL: java_lang_Thread_resume0()V */
void
Kaffe_java_lang_Thread_resume0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Thread_resume0(void*);
	java_lang_Thread_resume0(_P_[0].p);
}

/* SYMBOL: java_lang_Thread_interrupt0()V */
void
Kaffe_java_lang_Thread_interrupt0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Thread_interrupt0(void*);
	java_lang_Thread_interrupt0(_P_[0].p);
}
