/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_Throwable */

/* SYMBOL: java_lang_Throwable_printStackTrace0(Ljava/lang/Object;)V */
void
Kaffe_java_lang_Throwable_printStackTrace0_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_Throwable_printStackTrace0(void*, void*);
	java_lang_Throwable_printStackTrace0(_P_[1].p, _P_[0].p);
}

/* SYMBOL: java_lang_Throwable_fillInStackTrace()Ljava/lang/Throwable; */
void
Kaffe_java_lang_Throwable_fillInStackTrace_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Throwable* java_lang_Throwable_fillInStackTrace(void*);
	struct Hjava_lang_Throwable* ret = java_lang_Throwable_fillInStackTrace(_P_[0].p);
	return_ref(ret);
}
