/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_lang_UNIXProcess */

/* SYMBOL: java_lang_UNIXProcess_run()V */
void
Kaffe_java_lang_UNIXProcess_run_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_UNIXProcess_run(void*);
	java_lang_UNIXProcess_run(_P_[0].p);
}

/* SYMBOL: java_lang_UNIXProcess_forkAndExec([Ljava/lang/String;[Ljava/lang/String;)I */
void
Kaffe_java_lang_UNIXProcess_forkAndExec_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_lang_UNIXProcess_forkAndExec(void*, HArrayOfObject*, HArrayOfObject*);
	jint ret = java_lang_UNIXProcess_forkAndExec(_P_[2].p, _P_[1].p, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_lang_UNIXProcess_notifyReaders()V */
void
Kaffe_java_lang_UNIXProcess_notifyReaders_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_UNIXProcess_notifyReaders(void*);
	java_lang_UNIXProcess_notifyReaders(_P_[0].p);
}

/* SYMBOL: java_lang_UNIXProcess_destroy()V */
void
Kaffe_java_lang_UNIXProcess_destroy_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_lang_UNIXProcess_destroy(void*);
	java_lang_UNIXProcess_destroy(_P_[0].p);
}
