/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_net_InetAddressImpl */

/* SYMBOL: java_net_InetAddressImpl_getLocalHostName()Ljava/lang/String; */
void
Kaffe_java_net_InetAddressImpl_getLocalHostName_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_net_InetAddressImpl_getLocalHostName(void*);
	struct Hjava_lang_String* ret = java_net_InetAddressImpl_getLocalHostName(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_net_InetAddressImpl_makeAnyLocalAddress(Ljava/net/InetAddress;)V */
void
Kaffe_java_net_InetAddressImpl_makeAnyLocalAddress_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_InetAddressImpl_makeAnyLocalAddress(void*, void*);
	java_net_InetAddressImpl_makeAnyLocalAddress(_P_[1].p, _P_[0].p);
}

/* SYMBOL: java_net_InetAddressImpl_lookupAllHostAddr(Ljava/lang/String;)[[B */
void
Kaffe_java_net_InetAddressImpl_lookupAllHostAddr_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfArray* java_net_InetAddressImpl_lookupAllHostAddr(void*, void*);
	HArrayOfArray* ret = java_net_InetAddressImpl_lookupAllHostAddr(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: java_net_InetAddressImpl_getHostByAddr(I)Ljava/lang/String; */
void
Kaffe_java_net_InetAddressImpl_getHostByAddr_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* java_net_InetAddressImpl_getHostByAddr(void*, jint);
	struct Hjava_lang_String* ret = java_net_InetAddressImpl_getHostByAddr(_P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: java_net_InetAddressImpl_getInetFamily()I */
void
Kaffe_java_net_InetAddressImpl_getInetFamily_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_net_InetAddressImpl_getInetFamily(void*);
	jint ret = java_net_InetAddressImpl_getInetFamily(_P_[0].p);
	return_int(ret);
}
