/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_net_PlainSocketImpl */

/* SYMBOL: java_net_PlainSocketImpl_socketCreate(Z)V */
void
Kaffe_java_net_PlainSocketImpl_socketCreate_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_PlainSocketImpl_socketCreate(void*, jbool);
	java_net_PlainSocketImpl_socketCreate(_P_[1].p, _P_[0].i);
}

/* SYMBOL: java_net_PlainSocketImpl_socketConnect(Ljava/net/InetAddress;I)V */
void
Kaffe_java_net_PlainSocketImpl_socketConnect_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_PlainSocketImpl_socketConnect(void*, void*, jint);
	java_net_PlainSocketImpl_socketConnect(_P_[2].p, _P_[1].p, _P_[0].i);
}

/* SYMBOL: java_net_PlainSocketImpl_socketBind(Ljava/net/InetAddress;I)V */
void
Kaffe_java_net_PlainSocketImpl_socketBind_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_PlainSocketImpl_socketBind(void*, void*, jint);
	java_net_PlainSocketImpl_socketBind(_P_[2].p, _P_[1].p, _P_[0].i);
}

/* SYMBOL: java_net_PlainSocketImpl_socketListen(I)V */
void
Kaffe_java_net_PlainSocketImpl_socketListen_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_PlainSocketImpl_socketListen(void*, jint);
	java_net_PlainSocketImpl_socketListen(_P_[1].p, _P_[0].i);
}

/* SYMBOL: java_net_PlainSocketImpl_socketAccept(Ljava/net/SocketImpl;)V */
void
Kaffe_java_net_PlainSocketImpl_socketAccept_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_PlainSocketImpl_socketAccept(void*, void*);
	java_net_PlainSocketImpl_socketAccept(_P_[1].p, _P_[0].p);
}

/* SYMBOL: java_net_PlainSocketImpl_socketAvailable()I */
void
Kaffe_java_net_PlainSocketImpl_socketAvailable_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_net_PlainSocketImpl_socketAvailable(void*);
	jint ret = java_net_PlainSocketImpl_socketAvailable(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: java_net_PlainSocketImpl_socketClose()V */
void
Kaffe_java_net_PlainSocketImpl_socketClose_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_PlainSocketImpl_socketClose(void*);
	java_net_PlainSocketImpl_socketClose(_P_[0].p);
}

/* SYMBOL: java_net_PlainSocketImpl_initProto()V */
void
Kaffe_java_net_PlainSocketImpl_initProto_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_PlainSocketImpl_initProto();
	java_net_PlainSocketImpl_initProto();
}

/* SYMBOL: java_net_PlainSocketImpl_socketSetOption(IZLjava/lang/Object;)V */
void
Kaffe_java_net_PlainSocketImpl_socketSetOption_stub(stack_item* _P_, stack_item* _R_)
{
	extern void java_net_PlainSocketImpl_socketSetOption(void*, jint, jbool, void*);
	java_net_PlainSocketImpl_socketSetOption(_P_[3].p, _P_[2].i, _P_[1].i, _P_[0].p);
}

/* SYMBOL: java_net_PlainSocketImpl_socketGetOption(I)I */
void
Kaffe_java_net_PlainSocketImpl_socketGetOption_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_net_PlainSocketImpl_socketGetOption(void*, jint);
	jint ret = java_net_PlainSocketImpl_socketGetOption(_P_[1].p, _P_[0].i);
	return_int(ret);
}
