/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class java_net_SocketInputStream */

/* SYMBOL: java_net_SocketInputStream_socketRead([BII)I */
void
Kaffe_java_net_SocketInputStream_socketRead_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint java_net_SocketInputStream_socketRead(void*, HArrayOfByte*, jint, jint);
	jint ret = java_net_SocketInputStream_socketRead(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_int(ret);
}
