/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class sun_tools_debug_Agent */

/* SYMBOL: sun_tools_debug_Agent_systemThread(Ljava/lang/Thread;)Z */
void
Kaffe_sun_tools_debug_Agent_systemThread_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool sun_tools_debug_Agent_systemThread(void*);
	jbool ret = sun_tools_debug_Agent_systemThread(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_addSystemThread(Ljava/lang/Thread;)V */
void
Kaffe_sun_tools_debug_Agent_addSystemThread_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_addSystemThread(void*);
	sun_tools_debug_Agent_addSystemThread(_P_[0].p);
}

/* SYMBOL: sun_tools_debug_Agent_removeSystemThread(Ljava/lang/Thread;)V */
void
Kaffe_sun_tools_debug_Agent_removeSystemThread_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_removeSystemThread(void*);
	sun_tools_debug_Agent_removeSystemThread(_P_[0].p);
}

/* SYMBOL: sun_tools_debug_Agent_peek(I)I */
void
Kaffe_sun_tools_debug_Agent_peek_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint sun_tools_debug_Agent_peek(void*, jint);
	jint ret = sun_tools_debug_Agent_peek(_P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getThreadStatus(Ljava/lang/Thread;)I */
void
Kaffe_sun_tools_debug_Agent_getThreadStatus_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint sun_tools_debug_Agent_getThreadStatus(void*, void*);
	jint ret = sun_tools_debug_Agent_getThreadStatus(_P_[1].p, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getStackFrame(Ljava/lang/Thread;I)Lsun/tools/debug/StackFrame; */
void
Kaffe_sun_tools_debug_Agent_getStackFrame_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hsun_tools_debug_StackFrame* sun_tools_debug_Agent_getStackFrame(void*, void*, jint);
	struct Hsun_tools_debug_StackFrame* ret = sun_tools_debug_Agent_getStackFrame(_P_[2].p, _P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getMethods(Ljava/lang/Class;)[Lsun/tools/debug/Field; */
void
Kaffe_sun_tools_debug_Agent_getMethods_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* sun_tools_debug_Agent_getMethods(void*, void*);
	HArrayOfObject* ret = sun_tools_debug_Agent_getMethods(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getFields(Ljava/lang/Class;)[Lsun/tools/debug/Field; */
void
Kaffe_sun_tools_debug_Agent_getFields_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* sun_tools_debug_Agent_getFields(void*, void*);
	HArrayOfObject* ret = sun_tools_debug_Agent_getFields(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getClasses()[Ljava/lang/Class; */
void
Kaffe_sun_tools_debug_Agent_getClasses_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* sun_tools_debug_Agent_getClasses(void*);
	HArrayOfObject* ret = sun_tools_debug_Agent_getClasses(_P_[0].p);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getSlotObject(Ljava/lang/Object;I)Ljava/lang/Object; */
void
Kaffe_sun_tools_debug_Agent_getSlotObject_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* sun_tools_debug_Agent_getSlotObject(void*, void*, jint);
	struct Hjava_lang_Object* ret = sun_tools_debug_Agent_getSlotObject(_P_[2].p, _P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getSlotSignature(Ljava/lang/Class;I)[I */
void
Kaffe_sun_tools_debug_Agent_getSlotSignature_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfInt* sun_tools_debug_Agent_getSlotSignature(void*, void*, jint);
	HArrayOfInt* ret = sun_tools_debug_Agent_getSlotSignature(_P_[2].p, _P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getSlotBoolean(Ljava/lang/Object;I)Z */
void
Kaffe_sun_tools_debug_Agent_getSlotBoolean_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool sun_tools_debug_Agent_getSlotBoolean(void*, void*, jint);
	jbool ret = sun_tools_debug_Agent_getSlotBoolean(_P_[2].p, _P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getSlotInt(Ljava/lang/Object;I)I */
void
Kaffe_sun_tools_debug_Agent_getSlotInt_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint sun_tools_debug_Agent_getSlotInt(void*, void*, jint);
	jint ret = sun_tools_debug_Agent_getSlotInt(_P_[2].p, _P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getSlotLong(Ljava/lang/Object;I)J */
void
Kaffe_sun_tools_debug_Agent_getSlotLong_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong sun_tools_debug_Agent_getSlotLong(void*, void*, jint);
	jlong ret = sun_tools_debug_Agent_getSlotLong(_P_[2].p, _P_[1].p, _P_[0].i);
	return_long(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getSlotDouble(Ljava/lang/Object;I)D */
void
Kaffe_sun_tools_debug_Agent_getSlotDouble_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble sun_tools_debug_Agent_getSlotDouble(void*, void*, jint);
	jdouble ret = sun_tools_debug_Agent_getSlotDouble(_P_[2].p, _P_[1].p, _P_[0].i);
	return_double(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getSlotArray(Ljava/lang/Object;I)[Ljava/lang/Object; */
void
Kaffe_sun_tools_debug_Agent_getSlotArray_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* sun_tools_debug_Agent_getSlotArray(void*, void*, jint);
	HArrayOfObject* ret = sun_tools_debug_Agent_getSlotArray(_P_[2].p, _P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getStackObject(Ljava/lang/Thread;II)Ljava/lang/Object; */
void
Kaffe_sun_tools_debug_Agent_getStackObject_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_Object* sun_tools_debug_Agent_getStackObject(void*, void*, jint, jint);
	struct Hjava_lang_Object* ret = sun_tools_debug_Agent_getStackObject(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getStackBoolean(Ljava/lang/Thread;II)Z */
void
Kaffe_sun_tools_debug_Agent_getStackBoolean_stub(stack_item* _P_, stack_item* _R_)
{
	extern jbool sun_tools_debug_Agent_getStackBoolean(void*, void*, jint, jint);
	jbool ret = sun_tools_debug_Agent_getStackBoolean(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getStackInt(Ljava/lang/Thread;II)I */
void
Kaffe_sun_tools_debug_Agent_getStackInt_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint sun_tools_debug_Agent_getStackInt(void*, void*, jint, jint);
	jint ret = sun_tools_debug_Agent_getStackInt(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getStackLong(Ljava/lang/Thread;II)J */
void
Kaffe_sun_tools_debug_Agent_getStackLong_stub(stack_item* _P_, stack_item* _R_)
{
	extern jlong sun_tools_debug_Agent_getStackLong(void*, void*, jint, jint);
	jlong ret = sun_tools_debug_Agent_getStackLong(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_long(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getStackFloat(Ljava/lang/Thread;II)F */
void
Kaffe_sun_tools_debug_Agent_getStackFloat_stub(stack_item* _P_, stack_item* _R_)
{
	extern jfloat sun_tools_debug_Agent_getStackFloat(void*, void*, jint, jint);
	jfloat ret = sun_tools_debug_Agent_getStackFloat(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_float(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getStackDouble(Ljava/lang/Thread;II)D */
void
Kaffe_sun_tools_debug_Agent_getStackDouble_stub(stack_item* _P_, stack_item* _R_)
{
	extern jdouble sun_tools_debug_Agent_getStackDouble(void*, void*, jint, jint);
	jdouble ret = sun_tools_debug_Agent_getStackDouble(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_double(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getStackArray(Ljava/lang/Thread;II)[Ljava/lang/Object; */
void
Kaffe_sun_tools_debug_Agent_getStackArray_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfObject* sun_tools_debug_Agent_getStackArray(void*, void*, jint, jint);
	HArrayOfObject* ret = sun_tools_debug_Agent_getStackArray(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_lineno2pc(Ljava/lang/Class;I)Lsun/tools/debug/LineNumber; */
void
Kaffe_sun_tools_debug_Agent_lineno2pc_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hsun_tools_debug_LineNumber* sun_tools_debug_Agent_lineno2pc(void*, void*, jint);
	struct Hsun_tools_debug_LineNumber* ret = sun_tools_debug_Agent_lineno2pc(_P_[2].p, _P_[1].p, _P_[0].i);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_pc2lineno(Ljava/lang/Class;I)I */
void
Kaffe_sun_tools_debug_Agent_pc2lineno_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint sun_tools_debug_Agent_pc2lineno(void*, void*, jint);
	jint ret = sun_tools_debug_Agent_pc2lineno(_P_[2].p, _P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_method2pc(Ljava/lang/Class;I)I */
void
Kaffe_sun_tools_debug_Agent_method2pc_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint sun_tools_debug_Agent_method2pc(void*, void*, jint);
	jint ret = sun_tools_debug_Agent_method2pc(_P_[2].p, _P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_exceptionStackTrace(Ljava/lang/Throwable;)Ljava/lang/String; */
void
Kaffe_sun_tools_debug_Agent_exceptionStackTrace_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* sun_tools_debug_Agent_exceptionStackTrace(void*, void*);
	struct Hjava_lang_String* ret = sun_tools_debug_Agent_exceptionStackTrace(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_setSingleStep(Ljava/lang/Thread;Z)V */
void
Kaffe_sun_tools_debug_Agent_setSingleStep_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setSingleStep(void*, void*, jbool);
	sun_tools_debug_Agent_setSingleStep(_P_[2].p, _P_[1].p, _P_[0].i);
}

/* SYMBOL: sun_tools_debug_Agent_initAgent()V */
void
Kaffe_sun_tools_debug_Agent_initAgent_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_initAgent(void*);
	sun_tools_debug_Agent_initAgent(_P_[0].p);
}

/* SYMBOL: sun_tools_debug_Agent_getClassSourceName(Ljava/lang/Class;)Ljava/lang/String; */
void
Kaffe_sun_tools_debug_Agent_getClassSourceName_stub(stack_item* _P_, stack_item* _R_)
{
	extern struct Hjava_lang_String* sun_tools_debug_Agent_getClassSourceName(void*, void*);
	struct Hjava_lang_String* ret = sun_tools_debug_Agent_getClassSourceName(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getLinenumbers(Ljava/lang/Class;)[I */
void
Kaffe_sun_tools_debug_Agent_getLinenumbers_stub(stack_item* _P_, stack_item* _R_)
{
	extern HArrayOfInt* sun_tools_debug_Agent_getLinenumbers(void*, void*);
	HArrayOfInt* ret = sun_tools_debug_Agent_getLinenumbers(_P_[1].p, _P_[0].p);
	return_ref(ret);
}

/* SYMBOL: sun_tools_debug_Agent_getMethodLinenumber(Ljava/lang/Class;I)I */
void
Kaffe_sun_tools_debug_Agent_getMethodLinenumber_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint sun_tools_debug_Agent_getMethodLinenumber(void*, void*, jint);
	jint ret = sun_tools_debug_Agent_getMethodLinenumber(_P_[2].p, _P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_setSlotBoolean(Ljava/lang/Object;IZ)V */
void
Kaffe_sun_tools_debug_Agent_setSlotBoolean_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setSlotBoolean(void*, void*, jint, jbool);
	sun_tools_debug_Agent_setSlotBoolean(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: sun_tools_debug_Agent_setSlotInt(Ljava/lang/Object;II)V */
void
Kaffe_sun_tools_debug_Agent_setSlotInt_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setSlotInt(void*, void*, jint, jint);
	sun_tools_debug_Agent_setSlotInt(_P_[3].p, _P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: sun_tools_debug_Agent_setSlotLong(Ljava/lang/Object;IJ)V */
void
Kaffe_sun_tools_debug_Agent_setSlotLong_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setSlotLong(void*, void*, jint, jlong);
	sun_tools_debug_Agent_setSlotLong(_P_[4].p, _P_[3].p, _P_[2].i, _P_[0].l);
}

/* SYMBOL: sun_tools_debug_Agent_setSlotDouble(Ljava/lang/Object;ID)V */
void
Kaffe_sun_tools_debug_Agent_setSlotDouble_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setSlotDouble(void*, void*, jint, jdouble);
	sun_tools_debug_Agent_setSlotDouble(_P_[4].p, _P_[3].p, _P_[2].i, _P_[0].d);
}

/* SYMBOL: sun_tools_debug_Agent_setStackBoolean(Ljava/lang/Thread;IIZ)V */
void
Kaffe_sun_tools_debug_Agent_setStackBoolean_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setStackBoolean(void*, void*, jint, jint, jbool);
	sun_tools_debug_Agent_setStackBoolean(_P_[4].p, _P_[3].p, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: sun_tools_debug_Agent_setStackInt(Ljava/lang/Thread;III)V */
void
Kaffe_sun_tools_debug_Agent_setStackInt_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setStackInt(void*, void*, jint, jint, jint);
	sun_tools_debug_Agent_setStackInt(_P_[4].p, _P_[3].p, _P_[2].i, _P_[1].i, _P_[0].i);
}

/* SYMBOL: sun_tools_debug_Agent_setStackLong(Ljava/lang/Thread;IIJ)V */
void
Kaffe_sun_tools_debug_Agent_setStackLong_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setStackLong(void*, void*, jint, jint, jlong);
	sun_tools_debug_Agent_setStackLong(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[0].l);
}

/* SYMBOL: sun_tools_debug_Agent_setStackDouble(Ljava/lang/Thread;IID)V */
void
Kaffe_sun_tools_debug_Agent_setStackDouble_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_setStackDouble(void*, void*, jint, jint, jdouble);
	sun_tools_debug_Agent_setStackDouble(_P_[5].p, _P_[4].p, _P_[3].i, _P_[2].i, _P_[0].d);
}

/* SYMBOL: sun_tools_debug_Agent_objectId(Ljava/lang/Object;)I */
void
Kaffe_sun_tools_debug_Agent_objectId_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint sun_tools_debug_Agent_objectId(void*, void*);
	jint ret = sun_tools_debug_Agent_objectId(_P_[1].p, _P_[0].p);
	return_int(ret);
}

/* SYMBOL: sun_tools_debug_Agent_runMain(Ljava/lang/Class;[Ljava/lang/String;)V */
void
Kaffe_sun_tools_debug_Agent_runMain_stub(stack_item* _P_, stack_item* _R_)
{
	extern void sun_tools_debug_Agent_runMain(void*, void*, HArrayOfObject*);
	sun_tools_debug_Agent_runMain(_P_[2].p, _P_[1].p, _P_[0].p);
}
